### ISSUE TITLE
Garbo invents a timeframe for goal

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#164]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/3bbbbc0b-4242-4406-b061-dd67b7ed6fd7)

It's nice that Garbo tries to give a timeframe, but if it's annual it cannot be until 2023 (also that was last year so then its a result and not a goal...)

**Comment by irony** [comment]
![Image](https://github.com/Klimatbyran/beta/assets/395843/ef93f0bf-5bb3-458e-b5dc-89f2fe57d2f7)

Please verify that this works better?

**Comment by Greenheart** [comment]
I've checked the output from the latest report runs and the LLM started returning `year: null` in some cases, so the change mentioned above had some effect. However, the `goals` still seems to be unreliable for other reasons, for example like mentioned above here confusing past efforts or initiatives with specific and measurable goals.

Closing this issue since this is more of a data issue not relevant for the beta project. But we should continue improving how we get the `goals` and `initiatives`.
