### ISSUE TITLE
Recognise 0 as a value

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#167]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/9a360ed2-8575-4267-b99f-57d321ae54cb)

This company actually has 0 emissions in Scope 1 (and that's what facit says). It would be great if we could show the 0, so there is a distinction between 0 emissions and not reported. Same for Categories in scope 3 (where there should technically be a distinction between 0 emissions, n.a and not reported.

**Comment by Greenheart** [comment]
Good feedback! Yes, this would be a much better way to present the data.

This was introduced by the last minute hacks last week, but could easily be changed to check for explicit numbers and otherwise hide the scope.

Related: Or should we show `-` to indicate that nothing was reported, similar to how we do with categories?
