### ISSUE TITLE
Values correct but sum is wrong

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#190]
https://beta.klimatkollen.se/foretag/nolato-Q10601765

All values are right but total sum is still wrong

**Comment by Greenheart** [comment]
Seems like the `facit` data is missing completely, which makes the website trust the `wikidata` emissions to calculate the total. However, since `wikidata` is processed by garbo, we simply can not trust it as verified data. At least not until we fix https://github.com/Klimatbyran/garbo/issues/169.

The solution here is probably to make sure the wikidataId is included in the facit data (after the recent facit update), and then re-processing the report again.

But even better would be to read the facit data from the google sheet directly. So I will prioritize https://github.com/Klimatbyran/garbo/issues/178 before working on this one

**Comment by Almendra-ab** [comment]
Actually I reran the report, and now it works... so yeah.

**Comment by Greenheart** [comment]
Not ideal, but closing as resolved by the data update. Feel free to re-open if this happens again!
