### ISSUE TITLE
Garbo shows different results in Discord from site

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#196]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/949a7d21-a9bc-4a1b-a50d-97ccd9374dc8)

![Image](https://github.com/Klimatbyran/beta/assets/165904444/e3d392f7-c3a4-407e-9418-eed623c2eb11)

In Discord, Garbo shows the correct values for categories 1 and 2. On site, these are not reflected. It is **impossible** for me to double-check if and where in the json these values are stored or not.

**Comment by Almendra-ab** [comment]
Also for Lundin:
https://discord.com/channels/1049333222309371965/1258319108865265694

on site, there are emissiond displayed in scope 3

**Comment by Greenheart** [comment]
As of writing, the latest approved report for Corem was saved at `2024-06-18T13:55:16.926Z`, so the facit data could likely be outdated. And the beta site is prioritizing the facit data if available since it is the most reliable source.

For Lundin Mining, it shows the scope 3 emissions taken from the `wikidata` property, and these "scope 3 emissions" is  actually a bullshit number outputted by the LLM. As mentioned before, we need to solve https://github.com/Klimatbyran/garbo/issues/169 before we can trust the `wikidata` property again.

**Comment by Greenheart** [comment]
This seems to have been resolved when we updated the spreadsheet data about a month ago.
